# Generated by Django 3.2.4 on 2021-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryClothing',
            new_name='CategoryDeatil',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1622874351.8416266),
        ),
    ]
