# Generated by Django 3.2.4 on 2021-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210605_0625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDeatil',
            new_name='CategoryDetail',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1622874402.336401),
        ),
    ]
