# Generated by Django 3.2.4 on 2021-06-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('product', '0004_auto_20210605_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydetail',
            name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='filter.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='filter.categorydetail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1622875821.7580962),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryDetail',
        ),
    ]
