# Generated by Django 3.2.6 on 2021-09-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210907_2200'),
        ('product', '0007_auto_20210907_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='user.address'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(blank=True, default=1631019653.7458332),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.TextField(blank=True, default=1631019653.7458456, null=True),
        ),
    ]
