# Generated by Django 3.2.6 on 2021-09-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210908_1905'),
        ('product', '0011_auto_20210907_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='user.address'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(blank=True, default=1631095508.5594413),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.TextField(blank=True, default=1631095508.5594537, null=True),
        ),
    ]
