# Generated by Django 3.2.4 on 2021-06-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
        ('product', '0014_alter_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='article',
            name='category_detail',
            field=models.ManyToManyField(blank=True, related_name='article', to='filter.CategoryDetail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1622903773.664659),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='product.article')),
            ],
        ),
    ]
