# Generated by Django 3.2.4 on 2021-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1622995309.709205),
        ),
    ]
