# Generated by Django 3.2.4 on 2021-06-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_article_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='price',
            new_name='sale_price',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623046241.634584),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('discount_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='product.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
