# Generated by Django 3.2.4 on 2021-06-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210607_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sale_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623046388.1336575),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_price', to='product.article'),
        ),
    ]
