# Generated by Django 3.2.4 on 2021-06-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210607_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='discount_rate',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623046844.470157),
        ),
    ]
