# Generated by Django 3.2.4 on 2021-06-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210607_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623047036.8399856),
        ),
        migrations.AlterField(
            model_name='price',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_price', to='product.article'),
        ),
    ]
