# Generated by Django 3.2.4 on 2021-06-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20210607_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623047169.603839),
        ),
    ]
