# Generated by Django 3.2.4 on 2021-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210615_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623836988.9649312),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='image/'),
            preserve_default=False,
        ),
    ]
