# Generated by Django 3.2.4 on 2021-06-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210607_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1623048069.3777533),
        ),
        migrations.AlterField(
            model_name='price',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_price', to='product.article'),
        ),
    ]
