# Generated by Django 3.2.4 on 2021-06-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydetail',
            name='category',
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='filter.category'),
            preserve_default=False,
        ),
    ]
