# Generated by Django 3.2.4 on 2021-06-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20210606_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetail',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='filter.category'),
        ),
    ]
