# Generated by Django 3.2.4 on 2021-06-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_alter_categorydetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='filter.category'),
        ),
    ]
