# Generated by Django 3.2.8 on 2021-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, default=1633949494.1769378)),
                ('updated_at', models.TextField(blank=True, default=1633949494.1769493, null=True)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, default=1633949494.1769378)),
                ('updated_at', models.TextField(blank=True, default=1633949494.1769493, null=True)),
                ('content', models.CharField(max_length=255)),
                ('comment', models.ManyToManyField(blank=True, related_name='re_comment', to='social.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
