# Generated by Django 3.2.8 on 2021-10-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20211017_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(blank=True, default=1634436218.2566648),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.TextField(blank=True, default=1634436218.2566755, null=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(blank=True, default=1634436218.2566648),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='updated_at',
            field=models.TextField(blank=True, default=1634436218.2566755, null=True),
        ),
    ]
