# Generated by Django 3.2.6 on 2021-08-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210805_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(blank=True, default=1628133167.5334566),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.TextField(blank=True, default=1628133167.5334694, null=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(blank=True, default=1628133167.5334566),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='updated_at',
            field=models.TextField(blank=True, default=1628133167.5334694, null=True),
        ),
    ]
