# Generated by Django 3.2.4 on 2021-06-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_auto_20210621_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recomment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(blank=True, default=1624274148.8475008),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.TextField(blank=True, default=1624274148.8475125, null=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, default=1624274148.8475008)),
                ('updated_at', models.TextField(blank=True, default=1624274148.8475125, null=True)),
                ('content', models.CharField(max_length=255)),
                ('comment', models.ManyToManyField(blank=True, related_name='re_comment', to='social.Comment')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
