# Generated by Django 3.2.4 on 2021-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20210613_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recomment',
        ),
        migrations.AddField(
            model_name='recomment',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment', to='social.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623560670.3602538),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1623560670.3602538),
        ),
    ]
