# Generated by Django 3.2.6 on 2021-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20210922_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(blank=True, default=1632919712.6791008),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.TextField(blank=True, default=1632919712.679113, null=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(blank=True, default=1632919712.6791008),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='updated_at',
            field=models.TextField(blank=True, default=1632919712.679113, null=True),
        ),
    ]
