# Generated by Django 3.2.4 on 2021-06-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20210613_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='re_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623561738.2593968),
        ),
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
