# Generated by Django 3.2.4 on 2021-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20210613_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623562502.2824612),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='re_comment', to='social.Comment'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1623562502.2824612),
        ),
    ]
