# Generated by Django 3.2.4 on 2021-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=1624268479.0222745),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.TextField(blank=True, default=1624268479.0222883, null=True),
        ),
    ]
