# Generated by Django 3.2.6 on 2021-09-07 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210907_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(blank=True, default=1631021759.0528002),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.TextField(blank=True, default=1631021759.0528126, null=True),
        ),
    ]
