# Generated by Django 3.2.6 on 2021-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210922_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_agreed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_detailed',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(blank=True, default=1632919712.6791008),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.TextField(blank=True, default=1632919712.679113, null=True),
        ),
    ]
